name: Create Sdk release

on:
  push:
    tags:
      - "v*.*.*-SDK"

  workflow_dispatch:

jobs:
  publish:
    name: Release Sdk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Change wrapper permissions
        run: chmod +x ./generate-version.bash

      - name: Set tag version as env variable
        run: ./generate-version.bash

      - name: Set access token as env variable
        run: echo "ACCESS_TOKEN=${{ secrets.SECRET_GITHUB_CODE_ACCESS }}" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Publish to GitHub Package Registry ðŸš€
        run: ./gradlew :sdk:publish -PGIT_USER=${{ github.actor }} -PGIT_TOKEN=${{ secrets.SECRET_GITHUB_CODE }}
